### ISSUE TITLE
log spam

### ISSUE THREAD

**Issue by Starwaster** [schlosrat/FlightPlan#26]
When trying to do a transfer from Kerbin to Jool, I started getting 'failed to find any intercepts at all' log spam. It wouldn't stop even after switching to non-celestial menu options. 

It got so bad that the game started getting unplayable and I had to shut it down. 

Maybe it could be modified to produce a single log entry and maybe set a flag that would display the problem in the FP screen.

**Comment by schlosrat** [comment]
Thanks for reporting this. I'll see if I can replicate it or at least sort out why it would be endless.

Can you provide any info on what will trigger this? I've done transfers previously and not gotten this, so anything you can share that helps set it up to reproduce will be helpful and appreciated.

**Comment by schlosrat** [comment]
Well, this is curious. There's only one place in the code where that string appears, and it does appear in a logging function. The thing is, it's in a branch of dead code that can't be called. I just did a check to compare my latest Dev branch with the master and there are no differences. So, you shouldn't even be able to reach that line of code in any version built from the master or dev branch.

Can you check which version of FP you're running? If it's not the latest version, then please update to the latest and see if the problem vanishes. As things stand in the code today, it's not possible to reach that line.

**Comment by Starwaster** [comment]
AFAIK it's the latest version, but I'll doublecheck. It happened when trying to do a transfer to Jool It produced a maneuver that was nowhere near Jool and after awhile, the game started getting increasingly unplayable so I checked the log.

(A little while later)
It's easier to troubleshoot when not being mauled by an affectionate tabby girl. Okay so CKAN says 0.8.12 is installed. When was the last time that section of code was active?

**Comment by Starwaster** [comment]
This exact debug string is also present in KSP2 so now I don't actually know where this error is originating at all. This could be a KSP2 error. I only assumed it was FlightPlan because 

1. It happened while using FlightPlan
2. I checked in FlightPlan's code and found the string there so I didn't dig any further than that.

The exact line in the log was:
`[Debug] CheckEncounter: failed to find any intercepts at all`

What, if anything, does DebugLogger prepend to the log entry?

**Comment by schlosrat** [comment]
Now, I think we're getting somewhere! From what you've told me it's definitely not flightplan that's making the log entry. All flightplan log entries will begin with the words flight plan. But that doesn't mean it's not cause my flight plan. What I suspect now is the flight plan is calling the KSP to function that is causing the spam. I will look into where that is and how flightplan calls it.

**Comment by Starwaster** [comment]
I was starting from orbit over Kerbin. Have to look at KSP2 side again but I think as soon as the maneuver is created (which fails to intercept but comes close) that KSP2 code will lead it to that error. 

Haven't done much with it for the past few days because Phantom Liberty! 😛

**Comment by schlosrat** [comment]
I'm closing this as the log spam relates to a known issue reported in [Issue 41](https://github.com/schlosrat/FlightPlan/issues/49), which has workarounds that will prevent this. When that issue is resolved, then this one will be to.
