### ISSUE TITLE
Return From Moon condition stuck between saves

### ISSUE THREAD

**Issue by bespezzano** [schlosrat/FlightPlan#32]
Hi. Was testing a return to Minmus, then loaded a different save orbiting Kerbin, but the planner still shows I'm around Minmus

![image](https://github.com/schlosrat/FlightPlan/assets/24845837/f2386f09-53ae-441b-bd05-348346c0b522)

**Comment by schlosrat** [comment]
I see this, the status should automatically clear after a bit, and will also update as soon as there is a new status to report. This is an interesting corner case where its persisting across a load. I'll try to reproduce this and see if theres a way to detect a load and automatically clear the status.

**Comment by bespezzano** [comment]
Cool, let me know if you need any more testing

**Comment by schlosrat** [comment]
I believe this is an easy one. The effect you've seen is that there are only certain circumstances that cause the Flight Plan status to be updated. I've added monitoring of the VesselChanged message from the game and confirmed that this is now detected and the status is appropriately cleared.

You can test the bug very easily without needing to reload a game (although that will do it too). If you've got two vessels in orbit near each other where you can use the [ and ] keys to cycle between them, then create any sort of node for one of them using Flight Plan and subsequently switch to the other nearby vessel. Currently, in released versions of Flight Plan, this change is not detected and so the status remains until it would normally fade away or is replaced by some new status. In my Dev build of Flight Plan, this is now correctly detected and the status is cleared. As this is a fairly minor nuisance and not really affecting other features I'll leave this be for now and push the fix with the next update.

**Comment by schlosrat** [comment]
This issue has been mixed in Flight Plan 0.10.2. Please give that version a try.
