### ISSUE TITLE
Update to 0.10.2 not working

### ISSUE THREAD

**Issue by OnlyDabz** [schlosrat/FlightPlan#46]
says Error: B8934B49-FlightPlan-0.10.2.zip has SHA10BBDC9A7D9FB356D139FF7FCE5D0E4009BA91DA7 , should be 07737EEE69A10698037C3DF4B1DEAC1B84AC1284

**Comment by schlosrat** [comment]
The only thing that wasn't working is CKAN. The problem with that has been resolved in 0.10.2.1 (which is the same code as 0.10.2, except that CKAN likes it better now)
