### ISSUE TITLE
CKAN issue

### ISSUE THREAD

**Issue by OnlyDabz** [schlosrat/FlightPlan#51]
CKAN still does not have the proper update.

**Comment by schlosrat** [comment]
You may need to update or refresh CKAN. I'm not seeing the issue at my end.
![image](https://github.com/schlosrat/FlightPlan/assets/50781429/ef330918-cc5e-4d80-9be3-047d2cd728b1)

**Comment by Oliver-Saer** [comment]
Second this, I'm having this issue but I believe it's a CKAN issue as the meta repository has updated versions for several of mods which do not appear in the CKAN GUI for me - including FlightPlan.

**Comment by schlosrat** [comment]
Ahh, this makes sense. Thanks for sharing the solution.
